### ISSUE TITLE
`serve` is failing

### ISSUE THREAD

**Issue by gilles-yvetot** [oncilla/old-man-yells-at#11]
I was not able to run `serve` and it looks like [old-man-yells-at.herokuapp.com/](https://old-man-yells-at.herokuapp.com/) is down too (mentioning in case it is related)

**Comment by oncilla** [comment]
Hi @gilles-yvetot 

Heroku is down to their recent pricing changes. I'm not willing to pay for this 😆 

What error do you get on the serve?

**Comment by oncilla** [comment]
I'm happy to report that the service is back up at https://oncilla.github.io/old-man-yells-at/ thanks to the magic of github pages and webassembly

**Comment by oncilla** [comment]
Closing for now. Feel free to re-open if you encounter the error again
