### ISSUE TITLE
Slack does not like the crc check

### ISSUE THREAD

**Issue by jetersen** [oncilla/old-man-yells-at#21]
Slack does not like the image: `This image is a bit too big, even after resizing. A smaller file might help?`

The size of the file is less than 128kb so ~I assume it has do with the image dimensions which is `259x202`~ it is crc check that fails.

This is the one I tried with using the github.io page.

![old-man-yells-at-teamcity](https://github.com/oncilla/old-man-yells-at/assets/1661688/751870db-d690-45c5-a34f-8d04d9b06e00)

Use this target for the generator 

![teamcity](https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/TeamCity_Icon.svg/128px-TeamCity_Icon.svg.png)

**Comment by oncilla** [comment]
Hi @jetersen. Thanks for reporting.

I wonder if this is related to #20.
If you use the CLI, does it happen too?

**Comment by jetersen** [comment]
@oncilla Yes it seems like that would be the case 👍

The cli output works just fine.

**Comment by oncilla** [comment]
Ack. Thanks for checking it out.

Currently I'm unsure what the issue is. The webassembly and cli code should be exactly the same.
I will need to dig a bit when I get around to it.

**Comment by oncilla** [comment]
Hi @jetersen 

This should be fixed by #22. Could you double check if it is working now?

**Comment by jetersen** [comment]
@oncilla Yes! I can confirm that it works 👏 I am able to add it to slack 👍

![image](https://github.com/oncilla/old-man-yells-at/assets/1661688/b48a3cb2-b2e6-4efb-9605-455949da9b3a)

The `-too` is the test
