### ISSUE TITLE
readme: add explanation and installation guide

### ISSUE THREAD

**Issue by oncilla** [oncilla/old-man-yells-at#6]

**Comment by tdmalone** [comment]
Related - best install command might now be this?

```
go install github.com/oncilla/old-man-yells-at/cmd/old-man-yells-at@latest
```

**Comment by tdmalone** [comment]
Hmm actually although that appears to have 'installed' it, I can't figure out how to run it... a binary doesn't appear to be built.

**Comment by oncilla** [comment]
Hi @tdmalone

Great to see interest in this project :laughing: 

After running:
```
go install github.com/oncilla/old-man-yells-at/cmd/old-man-yells-at@latest
```
 you should have the binary available at `~/go/bin/old-man-yells-at`.

**Comment by tdmalone** [comment]
Sorry for the late response - when running that command I'm not getting a binary at that location.

However - I didn't notice this earlier (possibly the same thing happened last time I tried) but it appears I'm getting what appears to be an error (at least, exit code is 1) when running that `go install` command:
```
...
package github.com/oncilla/old-man-yells-at/cmd/old-man-yells-at
        imports github.com/oncilla/old-man-yells-at/server
        imports modernc.org/sqlite
        imports modernc.org/libc
        imports modernc.org/libc/unistd: build constraints exclude all Go files in /Users/tim/go/pkg/mod/modernc.org/libc@v0.0.0-20210126194511-2b2d365b45c2/unistd
```
(repeated for I think every dependency)

Tried running `go clean -modcache` first, per https://stackoverflow.com/a/73531307/1982136, but it didn't solve the problem.

It may just be my local Go install is somewhat messed up - and it's probably also a reminder that I really need to get into gear and finally figure out how Go works - but I guess what I was hoping for was some easy-to-follow installation steps so I didn't have to figure out Go before using this 😁

**Comment by oncilla** [comment]
Hi @tdmalone 

In the meantime I have added a [browser only version](https://github.com/oncilla/old-man-yells-at#browser-version) which is hosted at https://oncilla.github.io/old-man-yells-at/

If you still want to install it locally, we now attach the pre-built binaries to the [release assets](https://github.com/oncilla/old-man-yells-at/releases/tag/v0.1.1) which is now also [documented](https://github.com/oncilla/old-man-yells-at#cli-installation)
